spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8088
  servlet:
    context-path: /todo
